use ats;
CREATE Table airport(id VARCHAR(6),AIRPORT_NAME VARCHAR(25),COUNTRY_CODE VARCHAR(5));
SELECT * FROM airport;
INSERT INTO airport VALUES("AI0001","UNITED STATES","US");
INSERT INTO airport VALUES("AI0002","UNITED KINGDOM","UK");
DROP TABLE airport;